[functions]
  external_node_modules = ["@supabase", "bufferutil", "astro"]
  included_files = ["node_modules/@supabase/**/*"]
  node_bundler = "esbuild"
[build]
  command = "astro build"
  publish = "dist"